=== valentinFontaine/Site_CO77/.astro/collections/cartesGeo.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "feuille": {
      "type": "object",
      "properties": {
        "sud": {
          "type": "number",
          "minimum": -90,
          "maximum": 90
        },
        "ouest": {
          "type": "number",
          "minimum": -180,
          "maximum": 180
        },
        "nord": {
          "type": "number",
          "minimum": -90,
          "maximum": 90
        },
        "est": {
          "type": "number",
          "minimum": -180,
          "maximum": 180
        }
      },
      "required": [
        "sud",
        "ouest",
        "nord",
        "est"
      ]
    },
    "contour": {
      "minItems": 3,
      "type": "array",
      "items": {
        "type": "array",
        "prefixItems": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ]
      }
    },
    "rotation": {
      "default": 0,
      "anyOf": [
        {
          "type": "number",
          "const": 0
        },
        {
          "type": "number",
          "const": 90
        },
        {
          "type": "number",
          "const": 180
        },
        {
          "type": "number",
          "const": 270
        }
      ]
    },
    "source": {
      "type": "string"
    },
    "caleLe": {
      "type": "string",
      "format": "date-time"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "feuille",
    "contour"
  ]
}

=== valentinFontaine/Site_CO77/src/data/cartes-geo/Rocher_des_Demoiselles.json
{
  "feuille": {
    "nord": 48.390857191112936,
    "sud": 48.36441195415008,
    "ouest": 2.636117935180664,
    "est": 2.692422866821289
  },
  "contour": [
    [
      48.37209496092002,
      2.6428985595703125
    ],
    [
      48.3796226475104,
      2.653112411499024
    ],
    [
      48.38623696843915,
      2.664270401000977
    ],
    [
      48.389201729848764,
      2.671136856079102
    ],
    [
      48.3871492211149,
      2.688045501708985
    ],
    [
      48.37945157608451,
      2.6858139038085938
    ],
    [
      48.37825406000634,
      2.6857280731201176
    ],
    [
      48.376999489139195,
      2.6858997344970703
    ],
    [
      48.376144082185675,
      2.6865005493164062
    ],
    [
      48.37409104685752,
      2.6886463165283203
    ],
    [
      48.373406683351305,
      2.6892471313476562
    ],
    [
      48.36741811029687,
      2.6913070678710938
    ],
    [
      48.36679069522185,
      2.6911354064941406
    ],
    [
      48.36559288134223,
      2.6802349090576176
    ],
    [
      48.366163272417346,
      2.6689052581787114
    ],
    [
      48.36627734986583,
      2.6633262634277344
    ],
    [
      48.36479432310514,
      2.6610088348388676
    ],
    [
      48.36468024233491,
      2.659549713134766
    ]
  ],
  "rotation": 0,
  "source": "Rocher_des_Demoiselles.jpg",
  "caleLe": "2026-09-16"
}
